# Generated by Django 3.2.16 on 2022-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concessionaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('numero_de_carros', models.PositiveIntegerField()),
                ('funcionando', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Concesionarias',
            },
        ),
        migrations.AlterModelOptions(
            name='veiculos',
            options={'verbose_name_plural': 'Veículos'},
        ),
    ]
