# Generated by Django 3.2.16 on 2022-10-26 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221026_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculos',
            name='concessionaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.concessionaria'),
        ),
    ]
